# Generated by Django 5.2.5 on 2026-01-22 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['SUPER_ADMIN', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='department_fk',
            field=models.ForeignKey(blank=True, help_text='Department (Foreign Key)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='academics.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, help_text='Designation/Rank', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Employee ID for staff', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether user account is approved by admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('HOD', 'Head of Department'), ('FACULTY', 'Faculty Mentor'), ('STUDENT', 'Student'), ('PLACEMENT_CELL', 'Placement Cell'), ('PLACEMENT_OFFICER', 'Placement Officer'), ('INDUSTRY', 'Industry Supervisor'), ('EMPLOYER', 'Employer')], default='STUDENT', max_length=20),
        ),
    ]
