# Generated by Django 5.2.5 on 2026-01-22 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_approved_at_user_approved_by_user_department_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee ID', max_length=50, unique=True)),
                ('qualification', models.TextField(help_text='Educational qualifications')),
                ('specialization', models.CharField(help_text='Area of specialization', max_length=200)),
                ('years_of_experience', models.IntegerField(default=0, help_text='Years of teaching experience')),
                ('office_location', models.CharField(blank=True, help_text='Office room number/location', max_length=100)),
                ('office_hours', models.CharField(blank=True, help_text='e.g. Mon-Fri 10AM-12PM', max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='faculty_photos/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('linkedin_url', models.URLField(blank=True)),
                ('research_gate_url', models.URLField(blank=True)),
                ('google_scholar_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Profile',
                'verbose_name_plural': 'Faculty Profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
