# Generated by Django 4.2.28 on 2026-03-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_facultyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attendance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Overall attendance percentage', max_digits=5),
        ),
    ]
