# Generated by Django 4.2.28 on 2026-03-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Overall GPA', max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total marks obtained', max_digits=7),
        ),
    ]
