# Generated by Django 4.2.27 on 2025-12-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('stem_badge', models.FileField(blank=True, null=True, upload_to='badges/')),
                ('stem_badge_verified', models.BooleanField(default=False)),
                ('aiml_cert', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('aiml_cert_verified', models.BooleanField(default=False)),
                ('employability_score', models.IntegerField(default=0)),
            ],
        ),
    ]
