# Generated by Django 4.2.28 on 2026-03-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicadvisor'),
        ('students', '0005_studentprofile_academic_year_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='academics.course'),
        ),
    ]
