# Generated by Django 4.2.28 on 2026-03-04 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicadvisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0006_studentprofile_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, help_text='Percentage score', max_digits=5)),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('ai_feedback', models.TextField(help_text='Suggestions and tips based on performance')),
                ('ai_recommendations', models.TextField(help_text='Specific learning resources or topics to focus on')),
                ('test_details', models.JSONField(blank=True, default=dict, help_text='Question-wise student response data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Subject Evaluation',
                'verbose_name_plural': 'Subject Evaluations',
                'ordering': ['-created_at'],
            },
        ),
    ]
