# Generated by Django 4.2.27 on 2025-12-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SCREENING', 'In Screening'), ('INTERVIEW', 'Interview Scheduled'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('faculty_approved', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('department', models.CharField(blank=True, max_length=100)),
                ('competencies', models.CharField(help_text='Comma-separated tags', max_length=500)),
                ('stipend_range', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
