# Generated by Django 4.2.28 on 2026-03-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='eligibility_criteria',
            field=models.TextField(blank=True, help_text='Qualification, CGPA, backlogs etc.'),
        ),
    ]
