# Generated by Django 5.2.5 on 2026-01-22 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_course_subject_timeslot_timetable_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Lecture Notes, Videos, Books, Lab Manuals', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material Category',
                'verbose_name_plural': 'Material Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the material')),
                ('file', models.FileField(help_text='Upload PDF, DOC, PPT, Video, or other learning material', upload_to='learning_materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='Make material visible to all students')),
                ('access_level', models.CharField(choices=[('PUBLIC', 'Public - All Students'), ('DEPARTMENT', 'Department Only'), ('COURSE', 'Course Only'), ('SUBJECT', 'Subject Only')], default='SUBJECT', help_text='Access level for this material', max_length=20)),
                ('download_count', models.IntegerField(default=0, help_text='Number of times downloaded')),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(help_text='Subject this material belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='learning_materials', to='academics.subject')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'role': 'FACULTY'}, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Category of material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='elearning.materialcategory')),
            ],
            options={
                'verbose_name': 'Learning Material',
                'verbose_name_plural': 'Learning Materials',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded')], default='VIEW', max_length=20)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='elearning.learningmaterial')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='material_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Access',
                'verbose_name_plural': 'Material Accesses',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['material', 'student'], name='elearning_m_materia_5533bb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['subject', 'is_active'], name='elearning_l_subject_98ca3b_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['uploaded_by'], name='elearning_l_uploade_78d24c_idx'),
        ),
    ]
