# Generated by Django 5.2.5 on 2026-01-22 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_course_subject_timeslot_timetable_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Academic, Placement, Events, General, Fees, Exam', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announcement Category',
                'verbose_name_plural': 'Announcement Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Announcement content')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Priority level', max_length=10)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Announcement expiry date (optional)', null=True)),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users'), ('STUDENTS', 'Students Only'), ('FACULTY', 'Faculty Only'), ('DEPARTMENT', 'Department Only'), ('COURSE', 'Course Only'), ('BATCH', 'Batch Only')], default='ALL', help_text='Target audience for this announcement', max_length=20)),
                ('target_batch', models.CharField(blank=True, help_text='Target batch (e.g., 2024-2028)', max_length=50)),
                ('attachment', models.FileField(blank=True, help_text='Optional attachment file', null=True, upload_to='announcements/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether announcement is active')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin announcement to top')),
                ('posted_by', models.ForeignKey(limit_choices_to={'role__in': ['SUPER_ADMIN', 'ADMIN', 'HOD', 'FACULTY']}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(blank=True, help_text='Target department (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='academics.department')),
                ('category', models.ForeignKey(blank=True, help_text='Category of announcement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='announcements.announcementcategory')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-is_pinned', '-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement Read',
                'verbose_name_plural': 'Announcement Reads',
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField(help_text='Event date and time')),
                ('venue', models.CharField(help_text='Event venue/location', max_length=200)),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users'), ('STUDENTS', 'Students Only'), ('FACULTY', 'Faculty Only'), ('DEPARTMENT', 'Department Only')], default='ALL', max_length=20)),
                ('registration_required', models.BooleanField(default=False, help_text='Whether registration is required')),
                ('max_participants', models.IntegerField(blank=True, help_text='Maximum number of participants', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organizer', models.ForeignKey(limit_choices_to={'role__in': ['SUPER_ADMIN', 'ADMIN', 'HOD', 'FACULTY']}, on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='academics.department')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False, help_text='Whether student attended the event')),
                ('attendance_marked_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='announcements.event')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['target_audience', 'is_active'], name='announcemen_target__68ce5d_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['posted_at'], name='announcemen_posted__9d7b66_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['expiry_date'], name='announcemen_expiry__bb5922_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['announcement', 'user'], name='announcemen_announc_06457e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementread',
            unique_together={('announcement', 'user')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date', 'is_active'], name='announcemen_event_d_b6d569_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'student'], name='announcemen_event_i_a75a0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'student')},
        ),
    ]
