# Generated by Django 4.2.28 on 2026-03-06 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_individual',
            field=models.ForeignKey(blank=True, help_text='Target a specific student for personalized notices', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'All Users'), ('STUDENTS', 'Students Only'), ('FACULTY', 'Faculty Only'), ('DEPARTMENT', 'Department Only'), ('COURSE', 'Course Only'), ('BATCH', 'Batch Only'), ('INDIVIDUAL', 'Individual Student Only')], default='ALL', help_text='Target audience for this announcement', max_length=20),
        ),
    ]
