# Generated by Django 5.2.5 on 2026-01-22 11:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_course_subject_timeslot_timetable_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Quiz, Midterm, Assignment, Project', max_length=50, unique=True)),
                ('weightage', models.DecimalField(decimal_places=2, default=0.0, help_text='Weightage percentage in final marks', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assessment Type',
                'verbose_name_plural': 'Assessment Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, help_text='Marks obtained by student', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_marks', models.DecimalField(decimal_places=2, help_text='Maximum marks for this assessment', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('assessment_date', models.DateField(help_text='Date of assessment')),
                ('semester', models.IntegerField(help_text='Semester number', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='marks.assessmenttype')),
                ('entered_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Internal Mark',
                'verbose_name_plural': 'Internal Marks',
                'ordering': ['-assessment_date', 'student'],
                'indexes': [models.Index(fields=['student', 'subject', 'semester'], name='marks_inter_student_c794c1_idx'), models.Index(fields=['subject', 'assessment_type'], name='marks_inter_subject_3e8ffe_idx')],
                'unique_together': {('student', 'subject', 'assessment_type', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(help_text='Semester number', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('sgpa', models.DecimalField(decimal_places=2, default=0.0, help_text='Semester Grade Point Average', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('cgpa', models.DecimalField(decimal_places=2, default=0.0, help_text='Cumulative Grade Point Average', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('total_credits', models.IntegerField(default=0, help_text='Total credits in semester')),
                ('earned_credits', models.IntegerField(default=0, help_text='Credits earned')),
                ('passed_subjects', models.IntegerField(default=0)),
                ('failed_subjects', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semester Result',
                'verbose_name_plural': 'Semester Results',
                'ordering': ['-academic_year', '-semester', 'student'],
                'indexes': [models.Index(fields=['student', 'semester'], name='marks_semes_student_f628ee_idx')],
                'unique_together': {('student', 'semester', 'academic_year')},
            },
        ),
    ]
