# Generated by Django 4.2.28 on 2026-03-04 11:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0003_alter_department_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(help_text='Semester number', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('section', models.CharField(blank=True, help_text='Section (optional, e.g., A, B)', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_advisors', to='academics.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_advisors', to='academics.department')),
                ('faculty', models.ForeignKey(help_text='Faculty member designated as advisor', limit_choices_to={'role': 'FACULTY'}, on_delete=django.db.models.deletion.CASCADE, related_name='advised_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Advisor',
                'verbose_name_plural': 'Academic Advisors',
                'ordering': ['-academic_year', 'semester', 'course'],
                'unique_together': {('course', 'semester', 'academic_year', 'section', 'is_active')},
            },
        ),
    ]
